### ISSUE TITLE
과제 중 궁금한 점 

### ISSUE THREAD

**Issue by lycoris62** [lycoris62/sparta-todo-app#3]
1. 과제 중, 테스트만을 위해서 DTO에 `@Setter`, `@AllArgsConstructor`, `@NoArgsConstructor` 를 추가를 했었는데요, 처음부터 테스트를 고려한 DTO는 어떤 어노테이션만을 사용해서 쓰는 것이 좋을까요?? ([관련 커밋](https://github.com/lycoris62/sparta-todo-app/commit/832a6830427c68f56e37ed4071124a5aafee9df8))

**Comment by thesun4sky** [comment]
재윤님, 추가해주신 @Setter, @AllArgsConstructor, @NoArgsConstructor 를 추가해서 테스트 데이터를 만들 수 있지만
@Builder 어노테이션을 테스트용 생성자 메서드 위에 붙여서 사용하는 방법도 있습니다.
당연히 해당 생성자에 테스트용이라고 주석을 적어두어야 겠죠?

더 많은 방법이 있지만 필요한 어노테이션만 추가하는것이 좋습니다.
